"""
TagNaturalLanguageFilterStep: Filter natural language captions through Ollama.

This step takes the natural language caption generated by ToriiGate and
processes it through Ollama to remove artstyle references while preserving
all character and scene descriptions.

The model is managed at the batch level - loaded once at the start of the
batch and unloaded at the end, similar to how TagNaturalLanguageStep
manages the llama-server.
"""

import time
from pathlib import Path
from typing import Any

import requests

from caption_pipeline.core.context import ImageContext
from caption_pipeline.core.help import step_help
from caption_pipeline.core.step import PipelineStep
from caption_pipeline.prompts import NL_FILTER_SYSTEM_PROMPT
from caption_pipeline.utils import OllamaConfig, OllamaManager
from caption_pipeline.utils.logging_utils import (
    log,
    section,
)


@step_help(
    name="tag:nl_filter",
    description="Filter natural language captions through Ollama to remove artstyle references.",
    long_description="""This step sends the NL caption to an Ollama model with a system
prompt to remove artistic medium, style names, and technique references while
preserving all character and scene descriptions.

The model is managed at the batch level: loaded once at the start of the
batch, kept loaded for all images, and unloaded at the end. This provides
optimal performance for multiple images.

The system prompt is extracted to prompts/filter.py for maintainability.""",
    options=[
        {"flag": "--model NAME", "help": "Ollama model to use", "default": "deepseek-r1:14b"},
        {
            "flag": "--url URL",
            "help": "Ollama API URL",
            "default": "http://localhost:11434/api/chat",
        },
        {"flag": "--temperature FLOAT", "help": "Temperature for generation", "default": "0.3"},
        {"flag": "--retries INT", "help": "Max retries", "default": "3"},
        {"flag": "--timeout INT", "help": "Request timeout in seconds", "default": "120"},
        {"flag": "--no-backup", "help": "Don't back up original captions", "default": "backup"},
        {
            "flag": "--keep-alive INT",
            "help": "Seconds to keep model loaded after last request",
            "default": "3600",
        },
    ],
    example="tag:nl_filter --model llama3.2:3b",
)
class TagNaturalLanguageFilterStep(PipelineStep):
    """
    Filter natural language captions through Ollama to remove artstyle mentions.

    Model lifecycle:
    - Batch start: Model is loaded into Ollama memory
    - During batch: Model stays loaded (keep_alive=3600, renewed on each request)
    - Batch end: Model is unloaded from memory

    Uses the unified ResourceManager pattern (OllamaManager).
    """

    def __init__(
        self,
        model: str = "deepseek-r1:14b",
        ollama_url: str = "http://localhost:11434/api/chat",
        temperature: float = 0.3,
        max_retries: int = 3,
        timeout: int = 120,
        backup_original: bool = True,
        max_length_ratio: float = 1.2,
        keep_alive: int = 3600,
    ) -> None:
        """
        Initialize the natural language filter step.

        Args:
            model: Ollama model to use (default: deepseek-r1:14b)
            ollama_url: Ollama API URL (default: http://localhost:11434/api/chat)
            temperature: Temperature for generation (default: 0.3)
            max_retries: Maximum retries per file (default: 3)
            timeout: Request timeout in seconds (default: 120)
            backup_original: Whether to back up original captions (default: True)
            max_length_ratio: Maximum allowed length ratio (filtered/original).
                             If filtered exceeds this, retry. (default: 1.2)
            keep_alive: Seconds to keep model loaded (default: 3600)
        """
        self.model: str = model
        self.ollama_url: str = ollama_url
        self.temperature: float = temperature
        self.max_retries: int = max_retries
        self.timeout: int = timeout
        self.backup_original: bool = backup_original
        self.max_length_ratio: float = max_length_ratio
        self.keep_alive: int = keep_alive

        # Model manager (created in process_batch)
        self._manager: OllamaManager | None = None

        # System prompt from external file
        self._system_prompt: str = NL_FILTER_SYSTEM_PROMPT

    def name(self) -> str:
        """Return the step's unique identifier."""
        return "tag:natural_language_filter"

    def validate(self, context: ImageContext) -> bool:
        """Run if there's a natural language caption to filter."""
        nl_caption: list[str] = context.get_tags(section=2)
        return bool(nl_caption) and bool(nl_caption[0])

    def process(self, context: ImageContext) -> ImageContext | None:
        """
        Filter a single context's natural language caption.

        This runs after the model is already loaded by process_batch().
        """
        with section(f"Processing: {context.image_path.name}"):
            nl_caption: list[str] = context.get_tags(section=2)
            if not nl_caption or not nl_caption[0]:
                log.debug(f"No NL caption to filter for {context.image_path.name}")
                return context

            original_caption: str = nl_caption[0]

            # Process through Ollama with retries
            filtered, error = self._process_single_caption_with_retry(
                original_caption,
                context.image_path.name,
            )

            if filtered:
                # Store backup if requested
                if self.backup_original:
                    context.metadata["nl_original"] = original_caption

                # Update the context
                result: ImageContext = context.copy()
                result.set_tags([filtered], section=2)
                result.metadata["nl_filtered"] = True
                result.metadata["nl_model"] = self.model

                # === Show delta ===
                original_len = len(original_caption)
                filtered_len = len(filtered)
                diff = original_len - filtered_len

                log.info(
                    f"Filtered NL caption: "
                    f"{original_len} chars → {filtered_len} chars "
                    f"({'-' if diff > 0 else '+'}{diff if diff != 0 else 'no change'})"
                )

                # Show the delta using context from the difference
                if diff != 0 and filtered != original_caption:
                    import difflib

                    # Split by sentences for better diff
                    orig_sentences = [s.strip() for s in original_caption.split(". ") if s.strip()]
                    filt_sentences = [s.strip() for s in filtered.split(". ") if s.strip()]

                    # Find differences
                    matcher = difflib.SequenceMatcher(None, orig_sentences, filt_sentences)

                    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
                        if tag == "replace":
                            removed = ". ".join(orig_sentences[i1:i2])
                            added = ". ".join(filt_sentences[j1:j2])
                            log.info("Replaced:")
                            log.info(f"  - {removed}")
                            log.info(f"  + {added}")
                        elif tag == "delete":
                            removed = ". ".join(orig_sentences[i1:i2])
                            log.info(f"Removed: {removed}")
                        elif tag == "insert":
                            added = ". ".join(filt_sentences[j1:j2])
                            log.info(f"Added: {added}")

                # Full text at DEBUG level
                log.debug(f"Original: {original_caption}")
                log.debug(f"Filtered: {filtered}")

                return result
            else:
                log.warning(f"Failed to filter NL caption for {context.image_path.name}: {error}")
                return context

    def process_batch(
        self,
        contexts: list[ImageContext],
        show_progress: bool = True,
    ) -> list[ImageContext]:
        """
        Process multiple contexts with model loaded once for the entire batch.

        This is the key optimization: the model loads once at the start,
        stays loaded for all images, and unloads at the end.
        """
        if not contexts:
            return contexts

        # Filter valid contexts
        valid_contexts: list[ImageContext] = [ctx for ctx in contexts if self.validate(ctx)]
        if not valid_contexts:
            log.info("No valid contexts for NL filtering")
            return contexts

        log.info(f"Filtering NL captions for {len(valid_contexts)} images")

        results: list[ImageContext] = []

        # === BATCH-LEVEL MODEL MANAGEMENT ===
        # Load the model ONCE for the entire batch using ResourceManager pattern
        config = OllamaConfig(
            model=self.model,
            ollama_url=self.ollama_url,
            keep_alive=self.keep_alive,
        )

        with OllamaManager(config) as manager:
            self._manager = manager

            for context in valid_contexts:
                log.info(f"  Processing: {context.image_path.name}")
                # Each process() call uses the already-loaded model
                result: ImageContext | None = self.process(context)
                if result is not None:
                    results.append(result)

            self._manager = None
        # === MODEL UNLOADED HERE ===

        return results

    def _is_response_valid(
        self,
        original: str,
        filtered: str,
        attempt: int,
    ) -> tuple[bool, str | None]:
        """
        Validate the filtered response.

        Args:
            original: Original caption
            filtered: Filtered response
            attempt: Current attempt number

        Returns:
            Tuple of (is_valid, error_message)
        """
        # Check if response is too short
        if not filtered or len(filtered) < 10:
            return False, "Response is too short or empty"

        # Check if response is too short relative to original (< 30%)
        if len(filtered) < len(original) * 0.3:
            return False, (
                f"Response too short ({len(filtered)} chars, original {len(original)} chars)"
            )

        # Check if response is significantly longer than original
        if len(filtered) > len(original) * self.max_length_ratio:
            return False, (
                f"Response is longer than original ({len(filtered)} > "
                f"{len(original)} * {self.max_length_ratio})"
            )

        # If the response is identical to the original, it means the model
        # didn't remove anything - this is valid if there were no artstyle
        # references to remove
        if filtered == original:
            return True, None

        # Check if response contains explanations or analysis
        extra_markers = [
            "I've removed",
            "I have removed",
            "I removed",
            "Here is the filtered",
            "Here's the filtered",
            "After removing",
            "The filtered",
            "The modified",
            "```",
            "---",
        ]

        lower_response = filtered.lower()
        for marker in extra_markers:
            if lower_response.startswith(marker.lower()):
                return False, f"Response contains extra text at beginning: '{marker}'"

        if len(filtered) > len(original) and filtered.startswith(original):
            added = filtered[len(original) :].strip()
            return False, f"Response has extra text after original: '{added[:50]}...'"

        return True, None

    def _process_single_caption_with_retry(
        self,
        content: str,
        filename: str,
    ) -> tuple[str | None, str | None]:
        """
        Process a single caption through Ollama with retries for invalid responses.
        """
        last_error: str | None = None

        for attempt in range(self.max_retries):
            log.debug(f"Attempt {attempt + 1}/{self.max_retries} for {filename}")

            try:
                result, error = self._call_ollama(content)

                if error:
                    last_error = error
                    if attempt < self.max_retries - 1:
                        log.warning(
                            f"Attempt {attempt + 1} failed for {filename}: {error}. Retrying..."
                        )
                        time.sleep(1)
                        continue
                    return None, last_error

                is_valid, validation_error = self._is_response_valid(content, result, attempt)

                if is_valid:
                    return result, None

                last_error = validation_error or "Invalid response"

                if attempt == self.max_retries - 1:
                    # Only show full details at DEBUG level
                    log.debug("=" * 80)
                    log.debug(f"FAILED TO FILTER: {filename} after {self.max_retries} attempts")
                    log.debug("-" * 80)
                    log.debug("ORIGINAL CAPTION:")
                    log.debug(content)
                    log.debug("-" * 80)
                    log.debug("INVALID RESPONSE:")
                    log.debug(result)
                    log.debug("-" * 80)
                    log.debug(f"REASON: {last_error}")
                    log.debug("=" * 80)
                    return None, last_error
                else:
                    log.warning(
                        f"Attempt {attempt + 1} produced invalid response for {filename}: {last_error}"
                    )
                    log.debug(f"Response: {result}")
                    log.debug(f"Retrying {filename} (attempt {attempt + 2}/{self.max_retries})")
                    time.sleep(2)
                    continue

            except Exception as e:
                last_error = f"Unexpected error: {str(e)}"
                log.error(f"Unexpected error on attempt {attempt + 1} for {filename}: {e}")

                if attempt < self.max_retries - 1:
                    time.sleep(2)
                    continue

                log.error("=" * 80)
                log.error(f"FAILED TO FILTER: {filename} after {self.max_retries} attempts")
                log.error("-" * 80)
                log.error("ORIGINAL CAPTION:")
                log.error(content[:500] + "..." if len(content) > 500 else content)
                log.error("-" * 80)
                log.error(f"ERROR: {last_error}")
                log.error("=" * 80)
                return None, last_error

        return None, last_error or "Max retries exceeded"

    def _call_ollama(self, content: str) -> tuple[str | None, str | None]:
        """
        Call the Ollama API.

        The model is kept loaded by the OllamaManager context manager.
        """
        messages: list[dict[str, str]] = [
            {"role": "system", "content": self._system_prompt},
            {"role": "user", "content": content},
        ]

        # Use the manager's method if available (for consistent keep_alive)
        if self._manager:
            payload = self._manager.get_request_payload(messages)
            payload["temperature"] = self.temperature
            payload["top_p"] = 0.9
        else:
            # Fallback for single-image processing or testing
            payload = {
                "model": self.model,
                "messages": messages,
                "stream": False,
                "temperature": self.temperature,
                "top_p": 0.9,
                "keep_alive": self.keep_alive,
            }

        try:
            response = requests.post(
                self.ollama_url,
                json=payload,
                timeout=self.timeout,
            )
            response.raise_for_status()
            result: dict[str, Any] = response.json()

            if "message" in result and "content" in result["message"]:
                processed: str = result["message"]["content"].strip()
                return processed, None
            else:
                return None, f"Unexpected response format: {result}"

        except requests.exceptions.HTTPError as e:
            return None, f"HTTP {e.response.status_code}: {e.response.text[:200]}"
        except requests.exceptions.ConnectionError:
            return None, "Connection error: Could not connect to Ollama"
        except requests.exceptions.Timeout:
            return None, "Timeout: Request took too long"
        except requests.exceptions.RequestException as e:
            return None, f"Request error: {str(e)}"
        except Exception as e:
            return None, f"Unexpected error: {str(e)}"

    # === Convenience methods for direct file processing (backward compatibility) ===

    def filter_file_direct(
        self,
        file_path: Path,
        backup_dir: Path | None = None,
    ) -> bool:
        """
        Directly filter a file on disk (for backward compatibility).

        This is a convenience method that reads a file, processes it through
        Ollama, and writes the result back. It loads the model once per file.

        Args:
            file_path: Path to the file to filter
            backup_dir: Directory to store backups (optional)

        Returns:
            True if successful, False otherwise
        """
        if not file_path.exists():
            log.error(f"File not found: {file_path}")
            return False

        try:
            original_content: str = file_path.read_text(encoding="utf-8").strip()
            if not original_content:
                log.warning(f"File is empty: {file_path}")
                return False
        except Exception as e:
            log.error(f"Failed to read {file_path}: {e}")
            return False

        # Use the manager for single file
        config = OllamaConfig(
            model=self.model,
            ollama_url=self.ollama_url,
            keep_alive=self.keep_alive,
        )

        with OllamaManager(config) as manager:
            self._manager = manager
            filtered, error = self._process_single_caption_with_retry(
                original_content,
                file_path.name,
            )
            self._manager = None

        if filtered:
            # Create backup if requested
            if self.backup_original and backup_dir:
                backup_dir.mkdir(parents=True, exist_ok=True)
                backup_path: Path = backup_dir / file_path.name
                if not backup_path.exists():
                    backup_path.write_text(original_content, encoding="utf-8")

            # Write filtered content
            try:
                file_path.write_text(filtered, encoding="utf-8")
                log.info(
                    f"Filtered: {file_path.name} ({len(original_content)} → {len(filtered)} chars)"
                )
                return True
            except Exception as e:
                log.error(f"Failed to write {file_path}: {e}")
                return False
        else:
            log.error(f"Failed to filter {file_path.name}: {error}")
            return False

    def filter_directory(
        self,
        directory: Path,
        pattern: str = "*.txt",
        recursive: bool = False,
    ) -> tuple[int, int]:
        """
        Filter all matching files in a directory.

        Each file is processed with the model loaded once per batch.

        Args:
            directory: Directory to process
            pattern: File pattern to match (default: *.txt)
            recursive: Whether to process subdirectories

        Returns:
            Tuple of (success_count, failure_count)
        """
        directory = Path(directory)

        if recursive:
            files: list[Path] = list(directory.rglob(pattern))
        else:
            files = list(directory.glob(pattern))

        if not files:
            log.warning(f"No files matching {pattern} found in {directory}")
            return 0, 0

        log.info(f"Found {len(files)} files to filter")

        backup_dir: Path | None = directory / "backup" if self.backup_original else None

        success_count: int = 0
        failure_count: int = 0

        for file_path in files:
            if self.filter_file_direct(file_path, backup_dir):
                success_count += 1
            else:
                failure_count += 1

        log.info(f"Filtered {success_count}/{len(files)} files successfully")
        return success_count, failure_count
